### ISSUE TITLE
bad symbol running on ubuntu 22.04

### ISSUE THREAD

**Issue by gilesknap** [epics-extensions/c2dataviewer#2]
Hi,

I am getting the following error when running on ubuntu 22.04. 
```
# c2dv                                                                                                                                                        [13:32:55]
Traceback (most recent call last):
  File "/venv/bin/c2dv", line 5, in <module>
    from c2dataviewer.c2dv import main
  File "/venv/lib/python3.10/site-packages/c2dataviewer/__init__.py", line 7, in <module>
    from .imagev import imagev
  File "/venv/lib/python3.10/site-packages/c2dataviewer/imagev.py", line 23, in <module>
    from .control import ImageController
  File "/venv/lib/python3.10/site-packages/c2dataviewer/control/__init__.py", line 7, in <module>
    from .imagecontroller import ImageController
  File "/venv/lib/python3.10/site-packages/c2dataviewer/control/imagecontroller.py", line 23, in <module>
    from ..view.image_definitions import COLOR_MODE_MONO, COLOR_MODES
  File "/venv/lib/python3.10/site-packages/c2dataviewer/view/__init__.py", line 9, in <module>
    from .image_display import ImagePlotWidget
  File "/venv/lib/python3.10/site-packages/c2dataviewer/view/image_display.py", line 39, in <module>
    import pvaccess as pva
  File "/venv/lib/python3.10/site-packages/pvaccess/__init__.py", line 1, in <module>
    from .pvaccess import *
ImportError: /venv/lib/python3.10/site-packages/pvaccess/pvaccess.so: undefined symbol: _ZN5epics8pvAccess9Requester7messageERKSsNS0_11MessageTypeE
FAIL
```

The system I'm using has epics-base v 7.0.8 installed.

Any pointers appreciated.

Thanks,
giles

**Comment by echandler-anl** [comment]
Hi Giles, can you give us the list of python packages you have installed on the environment (i.e run pip list)?

**Comment by gilesknap** [comment]
BTW - I should have said I added epicscorelibs in an attempt to fix the issue that did not work.

```

root@pc0116: /workspaces/epics-base main!
# pip uninstall epicscorelibs                                                                                                                                                                                                                                  [6:43:47]
Found existing installation: epicscorelibs 7.0.7.99.0.2
Uninstalling epicscorelibs-7.0.7.99.0.2:
  Would remove:
    /venv/lib/python3.10/site-packages/epicscorelibs-7.0.7.99.0.2.dist-info/*
    /venv/lib/python3.10/site-packages/epicscorelibs/*
Proceed (Y/n)? y
  Successfully uninstalled epicscorelibs-7.0.7.99.0.2
 
root@pc0116: /workspaces/epics-base main!
# c2dv                                                                                                                                                                                                                                                         [6:43:56]
Traceback (most recent call last):
  File "/venv/bin/c2dv", line 5, in <module>
    from c2dataviewer.c2dv import main
  File "/venv/lib/python3.10/site-packages/c2dataviewer/__init__.py", line 7, in <module>
    from .imagev import imagev
  File "/venv/lib/python3.10/site-packages/c2dataviewer/imagev.py", line 23, in <module>
    from .control import ImageController
  File "/venv/lib/python3.10/site-packages/c2dataviewer/control/__init__.py", line 7, in <module>
    from .imagecontroller import ImageController
  File "/venv/lib/python3.10/site-packages/c2dataviewer/control/imagecontroller.py", line 23, in <module>
    from ..view.image_definitions import COLOR_MODE_MONO, COLOR_MODES
  File "/venv/lib/python3.10/site-packages/c2dataviewer/view/__init__.py", line 9, in <module>
    from .image_display import ImagePlotWidget
  File "/venv/lib/python3.10/site-packages/c2dataviewer/view/image_display.py", line 39, in <module>
    import pvaccess as pva
  File "/venv/lib/python3.10/site-packages/pvaccess/__init__.py", line 1, in <module>
    from .pvaccess import *
ImportError: /venv/lib/python3.10/site-packages/pvaccess/pvaccess.so: undefined symbol: _ZN5epics8pvAccess9Requester7messageERKSsNS0_11MessageTypeE
FAIL

root@pc0116: /workspaces/epics-base main!
# pip list                                                                                                                                                                                                                                                     [6:44:00]
Package        Version
-------------- -------
c2dataviewer   1.13.0
numpy          2.0.0
pip            22.0.2
psutil         6.0.0
pvapy          5.4.0
PyQt5          5.15.10
PyQt5-Qt5      5.15.2
```

**Comment by gilesknap** [comment]
If you have docker and would like to reproduce the error you only need to do this:
```
docker run -it ghcr.io/epics-containers/epics-base-developer:7.0.8ec2
apt update
apt install libgl1-mesa-glx libglib2.0-0
pip install c2dataviewer
c2dv
```

**Comment by sveseli** [comment]
Hi,

Like you mentioned you have epics libraries installed in this container, but you also set LD_LIBRARY_PATH, which points to the epics build and results in incompatible library being loaded. If you "unset LD_LIBRARY_PATH", the error message about missing symbol goes away. You still have a different issue that needs t be solved, but that is unrelated to epics libraries. 

<pre>
$ docker run -it ghcr.io/epics-containers/epics-base-developer:7.0.8ec2

root@eb6463effcc2:/# apt update
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
...
27 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@eb6463effcc2:/# apt install libgl1-mesa-glx libglib2.0-0
Reading package lists... Done
...
Processing triggers for libc-bin (2.35-0ubuntu3.6) ...

root@eb6463effcc2:/# pip install c2dataviewer
Collecting c2dataviewer
...
Successfully installed PyQt5-5.15.10 PyQt5-Qt5-5.15.2 PyQt5-sip-12.13.0 c2dataviewer-1.13.0 numpy-2.0.0 psutil-6.0.0 pvapy-5.4.0 pyqtgraph-0.12.4

root@eb6463effcc2:/# c2dv
Traceback (most recent call last):
  File "/venv/bin/c2dv", line 5, in <module>
    from c2dataviewer.c2dv import main
  File "/venv/lib/python3.10/site-packages/c2dataviewer/__init__.py", line 7, in <module>
    from .imagev import imagev
  File "/venv/lib/python3.10/site-packages/c2dataviewer/imagev.py", line 23, in <module>
    from .control import ImageController
  File "/venv/lib/python3.10/site-packages/c2dataviewer/control/__init__.py", line 7, in <module>
    from .imagecontroller import ImageController
  File "/venv/lib/python3.10/site-packages/c2dataviewer/control/imagecontroller.py", line 23, in <module>
    from ..view.image_definitions import COLOR_MODE_MONO, COLOR_MODES
  File "/venv/lib/python3.10/site-packages/c2dataviewer/view/__init__.py", line 9, in <module>
    from .image_display import ImagePlotWidget
  File "/venv/lib/python3.10/site-packages/c2dataviewer/view/image_display.py", line 39, in <module>
    import pvaccess as pva
  File "/venv/lib/python3.10/site-packages/pvaccess/__init__.py", line 1, in <module>
    from .pvaccess import *
ImportError: /venv/lib/python3.10/site-packages/pvaccess/pvaccess.so: undefined symbol: _ZN5epics8pvAccess9Requester7messageERKSsNS0_11MessageTypeE

root@eb6463effcc2:/# echo $LD_LIBRARY_PATH 
/epics/epics-base/lib/linux-x86_64

root@eb6463effcc2:/# unset LD_LIBRARY_PATH

root@eb6463effcc2:/# c2dv
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Fatal Python error: Aborted
...
</pre>

**Comment by gilesknap** [comment]
OK thanks! I believe I can fix that next issue.

**Comment by echandler-anl** [comment]
Issue has been resolved.
